// <auto-generated />
using System;
using DiskInfo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiskInfo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240222152031_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DiskInfo.Models.Disk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DiskFreeSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiskHealth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiskName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiskSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiskTotalSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiskType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HostSerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastCheckDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Disks");
                });
#pragma warning restore 612, 618
        }
    }
}
